package main

import (
	_ "technical-test/docs" // docs is generated by Swag CLI, you have to import it.
	"technical-test/internal/app"
)

// @title technical test API
func main() {
	// Setup and run the app
	err := app.SetupAndRunApp()
	if err != nil {
		panic(err)
	}
}
