package main

import (
	_ "auth-practice/docs" // docs is generated by Swag CLI, you have to import it.
	"auth-practice/internal/app"
)

// @title Auth Practice API
func main() {
	// Setup and run the app
	err := app.SetupAndRunApp()
	if err != nil {
		panic(err)
	}
}
