package app

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/swagger"

	_ "lms-backend/docs" // docs is generated by Swag CLI, you have to import it.
)

func AddSwaggerRoutes(app *fiber.App) {
	// setup swagger
	app.Get("/swagger/*", swagger.HandlerDefault)
}
